GET https://localhost:7196/user/fundWallet
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOGNlNWY5Zi03ZTRlLTQwOTQtODdlMi1hZTJkODgyMzQ2NmQiLCJqdGkiOiIwYTZiMTU1Ny1kN2UyLTQ5ZmQtYTlkYi1kNWU5NzAzY2FkN2QiLCJnaXZlbl9uYW1lIjoiQWJheW9taSIsImZhbWlseV9uYW1lIjoiT3lhaWZvIiwiZXhwIjoxNjcxNzYwNjIyLCJpc3MiOiJFQ29tbWVyY2VBcHAiLCJhdWQiOiJFQ29tbWVyY2VBcHAifQ.2aTmxOqseAaZaUekKRX5CxeSkDOjd5UEur3tp7VVJhg
