POST https://localhost:7196/cart/addtocart
Content-Type: application/json

{
    "cartId"     : "83C0FDFE-47DB-491C-A1B6-EAA8B730082C",
    "productId"  : "3F40F479-A1C0-48FE-9FE6-1B3895D1F997",
    "quantity"   : "2"
}